version: "3.8"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U odoo -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped

  odoo:
    image: odoo:17
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8069:8069"       # web
      - "8072:8072"       # longpolling (即時通知/聊天/看板拖拉)
    environment:
      HOST: db
      PORT: 5432
      USER: odoo
      PASSWORD: odoo
    volumes:
      - odoo-data:/var/lib/odoo              # Odoo filestore/資料
      - ./addons:/mnt/extra-addons           # 你的自製模組
      - ./odoo.conf:/etc/odoo/odoo.conf:ro   # 設定檔（如下）
    command: ["odoo", "-c", "/etc/odoo/odoo.conf", "--dev=reload"]  # 開發模式熱重載
    restart: unless-stopped

  # 可選：資料庫管理介面
  pgadmin:
    image: dpage/pgadmin4:8
    depends_on:
      db:
        condition: service_healthy
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    restart: unless-stopped

volumes:
  odoo-db-data:
  odoo-data:
